## Iterating on what the server setup would look like
## view to include in google_cloudbuild_trigger.init

steps: 

  - id: "docker-layer"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "FROM $_SERVER_NAME
        COPY --from=gcr.io/cloud-sql-connectors/cloud-sql-proxy /cloud-sql-proxy /cloudsql/cloud-sql-proxy" > Dockerfile-proxy;

        docker build -f Dockerfile-proxy -t $_PROXY_NAME .
  
  - id: "migrate"
    name: $_PROXY_NAME
    secretEnv:
      - DJANGO_ENV
      - DJANGO_SUPERUSER_PASSWORD
    env: 
      - USE_CLOUD_SQL_AUTH_PROXY=true
    entrypoint: /bin/bash
    args:
      - -c
      - |
        /cloudsql/cloud-sql-proxy ${_INSTANCE_CONNECTION_NAME} & sleep 2
        find / -name prime_database.sh
        bash /workspace/scripts/prime_database.sh


availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/django_settings-${_SUFFIX}/versions/latest
      env: DJANGO_ENV

    - versionName: projects/$PROJECT_ID/secrets/django_admin_password-${_SUFFIX}/versions/latest
      env: DJANGO_SUPERUSER_PASSWORD

options: 
  dynamic_substitutions: true
  #logging: CLOUD_LOGGING_ONLY

#serviceAccount: projects/${PROJECT_ID}/serviceAccounts/automation-6f21@glasnt-postjsscurl-6728.iam.gserviceaccount.com

substitutions:
  _SERVER_NAME: gcr.io/hsa-public/terraform-python-dynamic-webapp/server:v1.8.2
  _PROXY_NAME: gcr.io/${PROJECT_ID}/server-proxy
  _SUFFIX: "6f21"
  _INSTANCE_CONNECTION_NAME: glasnt-postjsscurl-6728:us-central1:psql-6f21